repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      - id: terraform_fmt
        args:
          - --args=-diff
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yml
          - --hook-config=--create-file-if-not-exist=true
          - --hook-config=--path-to-file=README.md
      - id: terraform_validate
      - id: terraform_tflint
        args:
          - "--args=--config=__GIT_WORKING_DIR__/modules/tflint.hcl"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces to replace line ending by the UNIX 'lf' character.
